# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/layouts/widget_slot.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetSlot(object):
    def setupUi(self, WidgetSlot):
        WidgetSlot.setObjectName("WidgetSlot")
        WidgetSlot.resize(493, 300)
        self.gridLayout = QtWidgets.QGridLayout(WidgetSlot)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(WidgetSlot)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border: 2px solid black;\n"
"border-radius: 6px;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.qline_slot = QtWidgets.QLineEdit(self.groupBox_3)
        self.qline_slot.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qline_slot.setText("")
        self.qline_slot.setAlignment(QtCore.Qt.AlignCenter)
        self.qline_slot.setPlaceholderText("")
        self.qline_slot.setObjectName("qline_slot")
        self.gridLayout_2.addWidget(self.qline_slot, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.qline_plate_digit = QtWidgets.QLineEdit(self.groupBox_3)
        self.qline_plate_digit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qline_plate_digit.setText("")
        self.qline_plate_digit.setAlignment(QtCore.Qt.AlignCenter)
        self.qline_plate_digit.setPlaceholderText("")
        self.qline_plate_digit.setObjectName("qline_plate_digit")
        self.gridLayout_2.addWidget(self.qline_plate_digit, 1, 1, 1, 1)
        self.qline_type_vehicle = QtWidgets.QLineEdit(self.groupBox_3)
        self.qline_type_vehicle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qline_type_vehicle.setText("")
        self.qline_type_vehicle.setAlignment(QtCore.Qt.AlignCenter)
        self.qline_type_vehicle.setPlaceholderText("")
        self.qline_type_vehicle.setObjectName("qline_type_vehicle")
        self.gridLayout_2.addWidget(self.qline_type_vehicle, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 1, 1, 1)
        self.qlabel_frame = QtWidgets.QLabel(WidgetSlot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qlabel_frame.sizePolicy().hasHeightForWidth())
        self.qlabel_frame.setSizePolicy(sizePolicy)
        self.qlabel_frame.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border: 2px solid black;\n"
"border-radius: 6px;\n"
"")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout.addWidget(self.qlabel_frame, 0, 0, 1, 1)

        self.retranslateUi(WidgetSlot)
        QtCore.QMetaObject.connectSlotsByName(WidgetSlot)

    def retranslateUi(self, WidgetSlot):
        _translate = QtCore.QCoreApplication.translate
        WidgetSlot.setWindowTitle(_translate("WidgetSlot", "Form"))
        self.label.setText(_translate("WidgetSlot", "Loại xe"))
        self.label_2.setText(_translate("WidgetSlot", "Biển số xe"))
        self.label_3.setText(_translate("WidgetSlot", "Chỗ đỗ"))
        self.qlabel_frame.setText(_translate("WidgetSlot", "qframe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetSlot = QtWidgets.QWidget()
    ui = Ui_WidgetSlot()
    ui.setupUi(WidgetSlot)
    WidgetSlot.show()
    sys.exit(app.exec_())
