# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/layouts/widget_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetIn(object):
    def setupUi(self, WidgetIn):
        WidgetIn.setObjectName("WidgetIn")
        WidgetIn.resize(1000, 789)
        WidgetIn.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(WidgetIn)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_A = QtWidgets.QGroupBox(WidgetIn)
        self.groupBox_A.setStyleSheet("")
        self.groupBox_A.setObjectName("groupBox_A")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_A)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_A = QtWidgets.QGridLayout()
        self.gridLayout_A.setObjectName("gridLayout_A")
        self.gridLayout_4.addLayout(self.gridLayout_A, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_A, 0, 0, 1, 1)
        self.groupBox_B = QtWidgets.QGroupBox(WidgetIn)
        self.groupBox_B.setObjectName("groupBox_B")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_B)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_B = QtWidgets.QGridLayout()
        self.gridLayout_B.setObjectName("gridLayout_B")
        self.gridLayout_5.addLayout(self.gridLayout_B, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_B, 0, 1, 1, 1)
        self.groupBox_C = QtWidgets.QGroupBox(WidgetIn)
        self.groupBox_C.setObjectName("groupBox_C")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_C)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_C = QtWidgets.QGridLayout()
        self.gridLayout_C.setObjectName("gridLayout_C")
        self.gridLayout_6.addLayout(self.gridLayout_C, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_C, 0, 2, 1, 1)
        self.groupBox_D = QtWidgets.QGroupBox(WidgetIn)
        self.groupBox_D.setObjectName("groupBox_D")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_D)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_D = QtWidgets.QGridLayout()
        self.gridLayout_D.setObjectName("gridLayout_D")
        self.gridLayout_7.addLayout(self.gridLayout_D, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_D, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(WidgetIn)
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_2.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border-radius: 6px;\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.qlabel_frame = QtWidgets.QLabel(self.groupBox_2)
        self.qlabel_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.qlabel_frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 6px;\n"
"border-radius: 6px;")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout_2.addWidget(self.qlabel_frame, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.groupBox_3.setStyleSheet("background-color: rgb(173, 221, 230);\n"
"border: 2px solid black;\n"
"border-radius: 6px;\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.qline_plate_digit = QtWidgets.QLineEdit(self.groupBox_3)
        self.qline_plate_digit.setGeometry(QtCore.QRect(180, 60, 111, 31))
        self.qline_plate_digit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qline_plate_digit.setText("")
        self.qline_plate_digit.setAlignment(QtCore.Qt.AlignCenter)
        self.qline_plate_digit.setPlaceholderText("")
        self.qline_plate_digit.setObjectName("qline_plate_digit")
        self.qline_type_vehicle = QtWidgets.QLineEdit(self.groupBox_3)
        self.qline_type_vehicle.setGeometry(QtCore.QRect(180, 20, 111, 31))
        self.qline_type_vehicle.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qline_type_vehicle.setText("")
        self.qline_type_vehicle.setAlignment(QtCore.Qt.AlignCenter)
        self.qline_type_vehicle.setPlaceholderText("")
        self.qline_type_vehicle.setObjectName("qline_type_vehicle")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 131, 31))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btn_apply = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_apply.setGeometry(QtCore.QRect(20, 150, 271, 91))
        self.btn_apply.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;\n"
"                color: #fff;\n"
"                border-radius: 25px;\n"
"                border: 2px solid #2980b9;\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #2980b9;\n"
"                padding-left: 15px;\n"
"                padding-top: 15px;\n"
"            }")
        self.btn_apply.setObjectName("btn_apply")
        self.qcomboBox_slot = QtWidgets.QComboBox(self.groupBox_3)
        self.qcomboBox_slot.setGeometry(QtCore.QRect(180, 100, 111, 31))
        self.qcomboBox_slot.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid black;\n"
"border-radius: 6px;")
        self.qcomboBox_slot.setObjectName("qcomboBox_slot")
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(WidgetIn)
        QtCore.QMetaObject.connectSlotsByName(WidgetIn)

    def retranslateUi(self, WidgetIn):
        _translate = QtCore.QCoreApplication.translate
        WidgetIn.setWindowTitle(_translate("WidgetIn", "Form"))
        self.groupBox_A.setTitle(_translate("WidgetIn", "Khu A (Ô tô)"))
        self.groupBox_B.setTitle(_translate("WidgetIn", "Khu B (Ô tô)"))
        self.groupBox_C.setTitle(_translate("WidgetIn", "Khu C (Xe máy)"))
        self.groupBox_D.setTitle(_translate("WidgetIn", "Khu D (Xe máy)"))
        self.qlabel_frame.setText(_translate("WidgetIn", "TextLabel"))
        self.label.setText(_translate("WidgetIn", "Loại xe"))
        self.label_2.setText(_translate("WidgetIn", "Biển số xe"))
        self.label_3.setText(_translate("WidgetIn", "Chỗ đỗ"))
        self.btn_apply.setText(_translate("WidgetIn", "Chấp nhận"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetIn = QtWidgets.QWidget()
    ui = Ui_WidgetIn()
    ui.setupUi(WidgetIn)
    WidgetIn.show()
    sys.exit(app.exec_())
